# Docker compose file for grafana, prometheus and prometheus pushgateway stack
version: "3.9"

services:
  grafana:
    container_name: comp-grafana
    hostname: comp-grafana
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-vol:/var/lib/grafana
  prometheus:
    container_name: comp-prometheus
    hostname: comp-prometheus
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  pushgateway:
    container_name: comp-pushgateway
    hostname: comp-pushgateway
    image: prom/pushgateway
    restart: always
    ports:
      - "9091:9091"

volumes:
  grafana-vol:
